site_name: Documentação Insper FabLab

theme:
  name: active-handout-theme
  # locale: pt_BR

docs_dir: content
site_dir: docs

site_url: https://insper-education.github.io/active-handout/
repo_name: "Documentação Insper Fablab"
repo_url: https://github.com/InsperFabLab/DocLab
edit_uri: edit/main/content/

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - termynal
  - active-handout:
      telemetry: true
      backend_url: https://example-backend.com.br/api/
      course_slug: Active Handout Example 2022
      tag_tree:
        - reference:
            - choice-exercise
            - parsons-exercise
            - text-exercise
        - grandparent-tag:
            - parent-tag:
                - child-tag

hooks:
  - hooks/custom_exercise.py

extra:
  custom_variables:
    var1: "*variables*"
    var2: material

markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: content
      check_paths: true

nav:
  - Home: index.md
  - Máquinas:
      - Laser:
          - Epilog Mini Helix 24: maquinas/laser/epilog/index.md
          - Duplotech 1080: maquinas/laser/duplotech1080/index.md
          - Duplotech 1610: maquinas/laser/duplotech1610/index.md
      - Fresadora:
          - Shopbot: maquinas/fresadora/shopbot/index.md
          - Mach Elite 3020: maquinas/fresadora/elite3020/index.md
      - Fresadora de precisão:
          - Roland MDX-40A: maquinas/fresadoraDePrecisao/mdx40a/index.md
          - Roland MDX-540: maquinas/fresadoraDePrecisao/mdx540/index.md
      - Impressora 3D:
          - Ultimaker S5: maquinas/impressora3d/ultimakerS5/index.md
          - Bambu Labs X1 Carbon: maquinas/impressora3d/bambuLabs/index.md
          - Ultimaker 2+: maquinas/impressora3d/ultimaker2plus/index.md
          - Zmorph: maquinas/impressora3d/zmorph/index.md
      - Cortadora de Vinil:
          - Roland Gx-24: maquinas/vinil/gx24/index.md
  - Projetos:
      - Cluster: https://insper.github.io/UpCluster/
      - Pista TurtleBot: projetos/pistaTurtlebot/index.md
